FROM node:26-alpine

WORKDIR /app

# command after the image name, will overwrite the CMD command of that image.


# with ENTRYPOINT, what ever you type after the image name, will be appended to the part written in ENTRYPOINT.
ENTRYPOINT [ "npm" ]